---
title: Table 1
output: pdf_document
geometry: margin=0.5cm
classoption: landscape
fontsize: 10pt
--- 

```{r echo=FALSE, warning=FALSE, message=FALSE}
### Table for DGP 1
library(magrittr)
library(kableExtra)
library(tidyverse)

df_R <- readr::read_csv("../rsimulation-dgp1-alt-2019-11-04-17-05-28.csv") %>%
  select(-c(additional_info))
df_m <- readr::read_csv("../../matlab_dgp1_simulation.csv") %>% 
  select(-c(additional_info)) %>% rename(mise1 = mse1) %>% rename(mise2 = mse2)

df_ind <- df_R[,1:2]
df_R <- df_R %>%  mutate(hd1 = hd1 / T, hd2 = hd2 / T) %>% select(-c(T, N)) #%>% 
  #rename_all(tibble::lst(~ paste0(., '_R')))
df_m <- df_m %>% mutate(hd1 = hd1 / T, hd2 = hd2 / T) %>% select(-c(T, N)) %>%
  rename_all(tibble::lst(~ paste0(., '_m')))

table1 <- dplyr::bind_cols(df_ind, df_R, df_m)
```

```{r}
### Construct LaTeX Tables 
table1 %>% 
  kable(format = 'latex', booktabs=TRUE, digits=3) %>%
  kable_styling(latex_options = "striped") %>% 
  add_header_above(header = c(" " = 2, "R" = 11, "Matlab" = 5)) %>% 
  add_header_above(header = c("DGP1" = 18))
```